// Fitted engine parameters. GENERATED by eval/fit-calibration.ts
// (grid search minimizing log loss on the dev split, seed 20261001).
// Fit details: see docs/v2-evaluation.md. Do not edit by hand.

export interface Calibration {
  version: string
  fittedOn: string
  method: string
  a: number
  pi: number
  T: number
  noneLogit: number
  clarifyBonus: number
  highCutoff: number
  mediumCutoff: number
  clarifyGap: number
}

export const CALIBRATION: Calibration = {
  version: 'fit-1',
  fittedOn: 'dev split of eval/queries.jsonl (50 queries; present + absent targets)',
  method: 'grid search: a in [0.5,1,1.5,2,2.5,3,4,5,6,8], pi in [0.5,0.6,0.7,0.8,0.9], T in [0.12,0.15,0.2,0.25,0.3,0.35,0.45,0.6,0.8,1,1.3,1.6,2,2.5,3], noneLogit in [-8,-6,-5,-4,-3,-2,-1,0,1,2,3,4,6,8,10,12]; objective: mean log loss; cutoffs derived on dev at top-1 precision >= 0.8 / >= 0.5 (min 3 queries)',
  a: 3,
  pi: 0.8,
  T: 1.3,
  noneLogit: 6,
  clarifyBonus: 1.7,
  highCutoff: 0.6,
  mediumCutoff: 0.12,
  clarifyGap: 0.12,
}
