// GENERATED by scripts/pick-heldout.ts (seed 20261001). Do not edit by hand.
// These photo ids are excluded from the retrieval index entirely: they are
// used to fit and test the "none of these" behavior (about 15% of the
// library). They still appear in the Library tab (browsing), never as
// search results, because they are not searchable.

export const HELDOUT_IDS: ReadonlySet<string> = new Set([
  'IMG_20231112_2055_20',
  'IMG_20241215_2240_51',
  'IMG_20240214_1120_25',
  'IMG_20251019_0820:00_1033',
  'IMG_20260124_0820_96',
  'IMG_20251019_1436_71',
  'IMG_20260215_1620:00_1021',
  'IMG_20250823_1945_52',
  'IMG_20250921_1652:00_1010',
  'IMG_20260307_2015:00_1017',
  'IMG_20250615_0940:00_1036',
  'IMG_20251021_1230_76',
  'IMG_20241215_1020_44',
  'IMG_20260214_2059_85',
  'IMG_20260111_1812:00_1040',
  'IMG_20251021_1245_77',
  'IMG_20240215_1005_28',
  'IMG_20250913_1420_91',
  'IMG_20250614_1915_64',
  'IMG_20250216_1530:00_1041',
  'IMG_20250614_1843_61',
  'IMGB_20251021_1245_6',
  'IMG_20250913_1500_92',
  'IMG_20260208_2130:00_1013',
])
