// Phase 6 prep: pick the held-out photos (15% of the library, excluded from
// the search index entirely) and the query-writing target pool.
// Deterministic: seeded shuffle, documented in the worklog.
//
// One command: bun scripts/pick-heldout.ts

import { readFileSync, writeFileSync } from 'fs'

interface Item { id: string; ts: string; source: string; deleted: boolean; generated: boolean; file: string }
const manifest = JSON.parse(readFileSync('./data/library-manifest.json', 'utf8'))
const items: Item[] = manifest.items

// mulberry32 seeded PRNG so the split is reproducible.
function mulberry32(seed: number) {
  return function () {
    let t = (seed += 0x6d2b79f5)
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}
const rand = mulberry32(20261001)

const livingCamera = items.filter((i) => i.source === 'camera' && !i.deleted)
const shuffled = [...livingCamera]
for (let i = shuffled.length - 1; i > 0; i--) {
  const j = Math.floor(rand() * (i + 1))
  ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
}

const heldoutCount = Math.round(items.length * 0.15) // 15% of the full library
const heldout = shuffled.slice(0, heldoutCount).map((i) => i.id)
const heldoutSet = new Set(heldout)

const searchableCamera = livingCamera.filter((i) => !heldoutSet.has(i.id))

// Query targets: 26 photos spread across searchable camera photos, spread over
// time; deterministic stride after seeded shuffle.
const stride = Math.floor(searchableCamera.length / 26)
const targets: string[] = []
for (let i = 0; i < searchableCamera.length && targets.length < 26; i += stride) targets.push(searchableCamera[i].id)

// Absent-target pool: 12 of the held-out photos get absent-target queries.
const absentTargets = heldout.slice(0, 12)

const ghosts = items.filter((i) => i.deleted).map((i) => i.id)

const out = {
  seed: 20261001,
  rule: '15 percent of the full library, seeded shuffle (mulberry32, seed 20261001)',
  heldout,
  queryTargets: targets,
  absentTargets,
  ghosts,
}
writeFileSync('./eval/splits.json', JSON.stringify(out, null, 2))

// Generate the heldout module the engine imports (searchable index only).
const ts = `// GENERATED by scripts/pick-heldout.ts (seed 20261001). Do not edit by hand.
// These photo ids are excluded from the retrieval index entirely: they are
// used to fit and test the "none of these" behavior (about 15% of the
// library). They still appear in the Library tab (browsing), never as
// search results, because they are not searchable.

export const HELDOUT_IDS: ReadonlySet<string> = new Set([
${heldout.map((h) => `  '${h}',`).join('\n')}
])
`
writeFileSync('./src/lib/engine2/heldout.ts', ts)

console.log('library:', items.length)
console.log('heldout (not searchable):', heldout.length)
console.log('searchable:', items.length - heldout.length)
console.log('query targets:', targets.length, '| absent targets:', absentTargets.length, '| ghosts:', ghosts.length)
